### ISSUE TITLE
Cannot compile without smooth font

### ISSUE THREAD

**Issue by MarkyAD** [Bodmer/TFT_eSPI#224]
drawString() needs an #ifdef SMOOTH_FONT. Undefining SMOOTH_FONT in user setup leads to symbol not declared error on "fontLoaded" because fontLoaded is in Extensions/Smooth_font.h and is only included if SMOOTH_FONT is defined.
```
TFT_eSPI/TFT_eSPI.cpp: In member function 'int16_t TFT_eSPI::drawString(const char*, int, int, int)':
TFT_eSPI/TFT_eSPI.cpp:4164:45: error: 'fontLoaded' was not declared in this scope
   bool freeFont = (font == 1 && gfxFont && !fontLoaded);

**Comment by Bodmer** [comment]
Thanks for reporting this I will correct this soon.

Leave SMOOTH_FONT enabled as in default for the time being.

**Comment by Bodmer** [comment]
Fixed, thanks for pointing out this bug.

**Comment by wawibu** [comment]
just updated to 1.1.1 and the issue is still coming up. SMOOTH_FONT still needs to be defined as otherwise frontLoaded is not declared at 4163 in TFT_eSPI.cpp

**Comment by Bodmer** [comment]
It looks like you do not have the version [with this commit](https://github.com/Bodmer/TFT_eSPI/commit/3d5ff73690edb48f29c1a46cc88bd4a41e0b4e33).  I think if you download the latest it should be fixed.  I may have forgotten to raise the issue number.

**Comment by Bodmer** [comment]
Yep, forgot to raise the version number! Please try the latest.

**Comment by Bodmer** [comment]
I have raised the version again to 1.1.3 with support for the WROVER kit.

I have created a release at 1.1.3 and this should be available via the library manager within 24 hours.

**Comment by wawibu** [comment]
would like to confirm that 1.1.3 is now available in PlatformIO and is fixed
Thanks again for your great support and this great library!
