### ISSUE TITLE
TTGo T-Display drawString positioning fault

### ISSUE THREAD

**Issue by vytux-com** [Bodmer/TFT_eSPI#801]
Somewhere between version 2.2.20 and 2.2.21 was introduced an error in the positioning of the drawString function 

Basically, this code snippet used to print the 4 sensor strings 5 pixels off the left border with the screen being in rotation 3

    char voltage[18];
    char weight[18];
    char c_temp[18];
    char e_temp[18];

    sprintf(voltage, " Voltage %6.2f V", battery_voltage);
    sprintf(c_temp,  " Temp 1  %6.2f C", current_temp);
    sprintf(e_temp,  " Temp 2  %6.2f C", cj_temp);
    sprintf(weight,  " Weight  %6.0f g", getScale());

    tft.setTextColor(TFT_BLACK);
    tft.pushImage(0, 0, 240, 135, vytis_blue);
    tft.drawString(F(" `` OpenStill ``"),24,4,2);

    tft.drawString(voltage, 5, 25);
    tft.drawString(c_temp, 5, 41);
    tft.drawString(e_temp, 5, 55);
    tft.drawString(weight, 5, 71);

Version 2.2.20 and before:
![PXL_20201023_122512672](https://user-images.githubusercontent.com/5370583/97007644-6ee4ea00-158d-11eb-8194-ace0d41ea8da.jpg)

Version 2.2.21 and later:
![PXL_20201023_125737911](https://user-images.githubusercontent.com/5370583/97007716-8b812200-158d-11eb-915c-88c2bb81de2c.jpg)

**Comment by vytux-com** [comment]
Screen Setup in PIO:
build_flags = 
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=135
  -DTFT_HEIGHT=240
  -DCGRAM_OFFSET=1
  -DTFT_MOSI=19
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=23
  -DTFT_BL=4
  -DTFT_BACKLIGHT_ON=HIGH
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_FONT6=1
  -DLOAD_FONT7=1
  -DLOAD_FONT8=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=6000000

**Comment by Bodmer** [comment]
There was a change as the fonts now permit partial off screen rendering.

This appears to only affect displays with an offset, I will investigate further.

Thanks for reporting this.

**Comment by Bodmer** [comment]
I think this has been corrected at 2.2.23.

The latests version is 2.3.2 on Github, and that one is working fine, but I think this was corrected at 2.2.23.

Please check with latest version.

**Comment by vytux-com** [comment]
I double-checked again but I am still having this issue with 2.3.2

I actually checked what feels like every version between 2.3.2 and 2.2.0 when trying to find the version where it broke

**Comment by Bodmer** [comment]
OK,

I used Setup25_TTGO_T_Display.h for my tests and this short sketch and it displays in the correct position.
```
  tft.init();
  tft.setRotation(1);
  tft.fillScreen(TFT_BLACK);
  tft.setTextSize(1);
  tft.setTextColor(TFT_WHITE,TFT_BLACK);
  tft.drawString(F(" `` OpenStill ``"),24,4,2);
  while(1);
```
Result:
![T_Display](https://user-images.githubusercontent.com/15824805/97245364-cc2da500-17f2-11eb-91ea-873fc4581778.jpg)

Can you test the same sketch.

**Comment by Bodmer** [comment]
Just checked and I am using version 2.2.23 for the above test.

**Comment by vytux-com** [comment]
OK, so your code worked for me as well.

After a little more investigation I found that the following line in my Setup routine was causing this issue: `tft.setTextDatum(MC_DATUM);`

Not sure what that is supposed to do as the rest seems to be working OK without it. I got that line from TTGo example I believe.

**Comment by Bodmer** [comment]
OK, that explains it, in earlier versions of the library the drawString code pulled the strings wholy onto the screen if the sketch tried to render off screen. This was to avoid character corruption of the RLE fonts. An update allowed all fonts to be partially off screen.

Hope you project now proceeds well.
